GROQ_API_KEY="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"
QDRANT_URL = "https://d9d3af35-3db6-4314-9aab-70f063e3ce90.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "WP6C4JXHI7P959mTsG9yjJXGpEnSE4JhKcyoBdZajaV479oDVGXlEQ"
